[package]
name = "string-sum"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.3.0"
rand = "0.7.3"

[lib]
name = "string_sum"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.1"
features = ["extension-module"]